# canopen documentation build configuration file, created by
# sphinx-quickstart on Mon Sep 19 22:15:46 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
from importlib import metadata
sys.path.insert(0, os.path.abspath('..'))

# General information about the project.
project = 'canopen'
copyright = '2016, Christian Sandberg'
author = 'Christian Sandberg'
# The full version, including alpha/beta/rc tags.
release = metadata.version('canopen')
# The short X.Y version.
version = '.'.join(release.split('.')[:2])

# -- General configuration ------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx_autodoc_typehints',
    'sphinx.ext.viewcode',
]

templates_path = ['_templates']
master_doc = 'index'
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

language = None

# Include documentation from both the class level and __init__
autoclass_content = 'both'

# -- Options for HTML output ----------------------------------------------

html_theme = 'default'

html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = 'canopendoc'

# -- Options for LaTeX output ---------------------------------------------

latex_documents = [
    (master_doc, 'canopen.tex', 'canopen Documentation',
     'Christian Sandberg', 'manual'),
]

# -- Options for manual page output ---------------------------------------

man_pages = [
    (master_doc, 'canopen', 'canopen Documentation',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'canopen', 'canopen Documentation',
     author, 'canopen', 'One line description of project.',
     'Miscellaneous'),
]

intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'can': ('https://python-can.readthedocs.io/en/stable/', None),
}
